import { NextResponse } from "next/server";
import { TItem } from "@/types/TItem"

const items: TItem[] = [
  {
    id: "1",
    name: "Nike Air Max",
    imageUrl: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
    price: 499,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43", "44"],
    color: ["black", "white"],
    description: "Komfortowe buty sportowe z poduszką powietrzną.",
    dateOfAdd: "2024-03-10",
  },
  {
    id: "2",
    name: "Adidas Ultraboost",
    imageUrl: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg",
    price: 599,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43", "44", "45"],
    color: ["blue", "black"],
    description: "Biegowe buty z najlepszą amortyzacją.",
    dateOfAdd: "2024-03-15",
  },
  {
    id: "3",
    name: "Puma RS-X",
    imageUrl: "https://images.pexels.com/photos/1192600/pexels-photo-1192600.jpeg",
    price: 450,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39", "40"],
    color: ["pink", "white"],
    description: "Stylowe buty lifestyle'owe o retro designie.",
    dateOfAdd: "2024-02-28",
  },
  {
    id: "4",
    name: "New Balance 574",
    imageUrl: "https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg",
    price: 399,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43"],
    color: ["grey", "black"],
    description: "Klasyczne buty sportowe na co dzień.",
    dateOfAdd: "2024-03-05",
  },
  {
    id: "5",
    name: "Reebok Classic Leather",
    imageUrl: "https://images.pexels.com/photos/568726/pexels-photo-568726.jpeg",
    price: 299,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39"],
    color: ["white"],
    description: "Ponadczasowy styl i komfort.",
    dateOfAdd: "2024-03-18",
  },
  {
    id: "6",
    name: "Nike Air Force 1",
    imageUrl: "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
    price: 550,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43", "44"],
    color: ["white", "black"],
    description: "Legendarne buty w streetwearowym stylu.",
    dateOfAdd: "2024-03-22",
  },
  {
    id: "7",
    name: "Vans Old Skool",
    imageUrl: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg",
    price: 320,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39", "40"],
    color: ["black", "white"],
    description: "Klasyczne sneakersy na deskorolkę.",
    dateOfAdd: "2024-03-12",
  },
  {
    id: "8",
    name: "Converse Chuck Taylor",
    imageUrl: "https://images.pexels.com/photos/2529148/pexels-photo-2529148.jpeg",
    price: 280,
    type: "shoes",
    gender: "men",
    size: ["39", "40", "41", "42", "43"],
    color: ["red", "black"],
    description: "Ikoniczne trampki, które nigdy nie wychodzą z mody.",
    dateOfAdd: "2024-02-25",
  },
  {
    id: "9",
    name: "Timberland 6-Inch",
    imageUrl: "https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg",
    price: 799,
    type: "shoes",
    gender: "men",
    size: ["41", "42", "43", "44"],
    color: ["brown", "yellow"],
    description: "Wytrzymałe i wodoodporne buty na zimę.",
    dateOfAdd: "2024-03-01",
  },
  {
    id: "10",
    name: "Dr. Martens 1460",
    imageUrl: "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
    price: 750,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39", "40"],
    color: ["black"],
    description: "Solidne buty skórzane w rockowym stylu.",
    dateOfAdd: "2024-02-20",
  },
  {
    id: "11",
    name: "Nike Blazer Mid '77",
    imageUrl: "https://images.pexels.com/photos/1192600/pexels-photo-1192600.jpeg",
    price: 520,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43"],
    color: ["white", "blue"],
    description: "Koszykarskie buty retro w nowoczesnym wydaniu.",
    dateOfAdd: "2024-03-08",
  },
  {
    id: "12",
    name: "Adidas Gazelle",
    imageUrl: "https://images.pexels.com/photos/568726/pexels-photo-568726.jpeg",
    price: 370,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39", "40"],
    color: ["blue", "black"],
    description: "Kultowy model od lat 60.",
    dateOfAdd: "2024-03-17",
  },
  {
    id: "13",
    name: "Balenciaga Triple S",
    imageUrl: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg",
    price: 3500,
    type: "shoes",
    gender: "men",
    size: ["41", "42", "43", "44", "45"],
    color: ["grey", "black"],
    description: "Luksusowe buty z modnym, masywnym designem.",
    dateOfAdd: "2024-03-03",
  },
  {
    id: "14",
    name: "Yeezy Boost 350 V2",
    imageUrl: "https://images.pexels.com/photos/1192600/pexels-photo-1192600.jpeg",
    price: 1800,
    type: "shoes",
    gender: "men",
    size: ["40", "41", "42", "43", "44"],
    color: ["black", "grey"],
    description: "Ekskluzywne sneakersy od Kanye Westa.",
    dateOfAdd: "2024-03-19",
  },
  {
    id: "15",
    name: "Nike SB Dunk Low",
    imageUrl: "https://images.pexels.com/photos/994517/pexels-photo-994517.jpeg",
    price: 700,
    type: "shoes",
    gender: "girl",
    size: ["36", "37", "38", "39", "40"],
    color: ["red", "black"],
    description: "Profesjonalne buty do skateboardingu.",
    dateOfAdd: "2024-03-06",
  },
];


export async function GET(req: Request, { params } : {params : {id : string}}) {
  const { id } = params;

  const product = items.find(item => item.id === id)

  if (!product) {
    return NextResponse.json({error: "Nieznaleziono produkty", isError: true})
  }

  return NextResponse.json(product);
}